openapi: 3.0.1
info:
  title: CoolingCoilFiware
  description: API specification for IoT platform including Cooling Coil Fiwares
  version: '1.0'
servers:
- url: http://fiware.rwth-aachen.de/
paths:
  /v2/entities:
    get:
      tags:
      - Cooling Coil Fiware
      summary: Get Cooling Coil Fiwares
      description: Retrieves available cooling coil fiwares
      operationId: getCoolingCoilFiwares
      parameters:
      - name: type
        in: query
        description: Entity type, to avoid ambiguity in case there are several entities
          with the same entity id.
        schema:
          type: string
          default: CoolingCoilFiware
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '200':
          description: Successful operation. Returns the entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoolingCoilFiware'
        '404':
          description: Cooling Coil Fiware not found.
          content: {}
        '500':
          description: Internal server error.
          content: {}
    post:
      tags:
      - Cooling Coil Fiware
      summary: Create Cooling Coil Fiware
      description: Creates a new Cooling Coil Fiware entity in the system.
      operationId: createCoolingCoilFiware
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoolingCoilFiware'
            example:
              id: coolingcoilfiware001
              type: CoolingCoilFiware
      parameters:
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '201':
          description: Cooling Coil Fiware successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoolingCoilFiware'
        '400':
          description: Invalid input data.
          content: {}
        '500':
          description: Internal server error.
          content: {}
components:
  schemas:
    CoolingCoilFiware:
      additionalProperties: true
      description: Extends the CoolingCoil class to include Fiware-specific properties.
      properties:
        id:
          description: 'Id of an entity in an NGSI context broker. Allowed characters
            are the ones in the plain ASCII set, except the following ones: control
            characters, whitespace, &, ?, / and #.'
          example: Bcn-Welt
          maxLength: 256
          minLength: 1
          title: Entity Id
          type: string
        type:
          default: CoolingCoil
          title: Type
          type: string
        hasLocation:
          anyOf:
          - type: string
          - type: 'null'
          default: null
          title: Haslocation
        brand:
          anyOf:
          - type: string
          - type: 'null'
          default: null
          title: Brand
        fanSpeed:
          anyOf:
          - type: number
          - type: 'null'
          default: 0
          title: Fanspeed
      required:
      - id
      title: CoolingCoilFiware
      type: object
