openapi: 3.0.1
info:
  title: HotelFiware
  description: API specification for IoT platform including Hotel Fiwares
  version: '1.0'
servers:
- url: http://fiware.rwth-aachen.de/
paths:
  /v2/entities:
    get:
      tags:
      - Hotel Fiware
      summary: Get Hotel Fiwares
      description: Retrieves available hotel fiwares
      operationId: getHotelFiwares
      parameters:
      - name: type
        in: query
        description: Entity type, to avoid ambiguity in case there are several entities
          with the same entity id.
        schema:
          type: string
          default: HotelFiware
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '200':
          description: Successful operation. Returns the entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HotelFiware'
        '404':
          description: Hotel Fiware not found.
          content: {}
        '500':
          description: Internal server error.
          content: {}
    post:
      tags:
      - Hotel Fiware
      summary: Create Hotel Fiware
      description: Creates a new Hotel Fiware entity in the system.
      operationId: createHotelFiware
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HotelFiware'
            example:
              id: hotelfiware001
              type: HotelFiware
              name: Hotel Example
      parameters:
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '201':
          description: Hotel Fiware successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HotelFiware'
        '400':
          description: Invalid input data.
          content: {}
        '500':
          description: Internal server error.
          content: {}
components:
  schemas:
    HotelFiware:
      additionalProperties: true
      description: Extends the Hotel class to include Fiware-specific properties.
      properties:
        id:
          description: 'Id of an entity in an NGSI context broker. Allowed characters
            are the ones in the plain ASCII set, except the following ones: control
            characters, whitespace, &, ?, / and #.'
          example: Bcn-Welt
          maxLength: 256
          minLength: 1
          title: Entity Id
          type: string
        type:
          default: Hotel
          title: Type
          type: string
        name:
          default: null
          title: Name
          type: string
        address:
          anyOf:
          - type: string
          - type: 'null'
          default: null
          title: Address
      required:
      - id
      title: HotelFiware
      type: object
