openapi: 3.0.1
info:
  title: FreshAirVentilationFiware
  description: API specification for IoT platform including Fresh Air Ventilation
    Fiwares
  version: '1.0'
servers:
- url: http://fiware.rwth-aachen.de/
paths:
  /v2/entities:
    get:
      tags:
      - Fresh Air Ventilation Fiware
      summary: Get Fresh Air Ventilation Fiwares
      description: Retrieves available fresh air ventilation fiwares
      operationId: getFreshAirVentilationFiwares
      parameters:
      - name: type
        in: query
        description: Entity type, to avoid ambiguity in case there are several entities
          with the same entity id.
        schema:
          type: string
          default: FreshAirVentilationFiware
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '200':
          description: Successful operation. Returns the entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FreshAirVentilationFiware'
        '404':
          description: Fresh Air Ventilation Fiware not found.
          content: {}
        '500':
          description: Internal server error.
          content: {}
    post:
      tags:
      - Fresh Air Ventilation Fiware
      summary: Create Fresh Air Ventilation Fiware
      description: Creates a new Fresh Air Ventilation Fiware entity in the system.
      operationId: createFreshAirVentilationFiware
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FreshAirVentilationFiware'
            example:
              id: freshairventilationfiware001
              type: FreshAirVentilationFiware
      parameters:
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '201':
          description: Fresh Air Ventilation Fiware successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FreshAirVentilationFiware'
        '400':
          description: Invalid input data.
          content: {}
        '500':
          description: Internal server error.
          content: {}
components:
  schemas:
    FreshAirVentilationFiware:
      additionalProperties: true
      description: Extends the FreshAirVentilation class to include Fiware-specific
        properties.
      properties:
        id:
          description: 'Id of an entity in an NGSI context broker. Allowed characters
            are the ones in the plain ASCII set, except the following ones: control
            characters, whitespace, &, ?, / and #.'
          example: Bcn-Welt
          maxLength: 256
          minLength: 1
          title: Entity Id
          type: string
        type:
          default: FreshAirVentilation
          title: Type
          type: string
        hasLocation:
          anyOf:
          - type: string
          - type: 'null'
          default: null
          title: Haslocation
        airFlowSetpoint:
          anyOf:
          - type: number
          - type: 'null'
          default: 0
          title: Airflowsetpoint
      required:
      - id
      title: FreshAirVentilationFiware
      type: object
