openapi: 3.0.1
info:
  title: ActuatorFiware
  description: API specification for IoT platform including Actuator Fiwares
  version: '1.0'
servers:
- url: http://fiware.rwth-aachen.de/
paths:
  /v2/entities:
    get:
      tags:
      - Actuator Fiware
      summary: Get Actuator Fiwares
      description: Retrieves available actuator fiwares
      operationId: getActuatorFiwares
      parameters:
      - name: type
        in: query
        description: Entity type, to avoid ambiguity in case there are several entities
          with the same entity id.
        schema:
          type: string
          default: ActuatorFiware
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '200':
          description: Successful operation. Returns the entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActuatorFiware'
        '404':
          description: Actuator Fiware not found.
          content: {}
        '500':
          description: Internal server error.
          content: {}
    post:
      tags:
      - Actuator Fiware
      summary: Create Actuator Fiware
      description: Creates a new Actuator Fiware entity in the system.
      operationId: createActuatorFiware
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActuatorFiware'
            example:
              id: actuatorfiware001
              type: ActuatorFiware
      parameters:
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '201':
          description: Actuator Fiware successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActuatorFiware'
        '400':
          description: Invalid input data.
          content: {}
        '500':
          description: Internal server error.
          content: {}
components:
  schemas:
    ActuatorFiware:
      additionalProperties: true
      description: Base class for Fiware-compatible actuators.
      properties:
        id:
          description: 'Id of an entity in an NGSI context broker. Allowed characters
            are the ones in the plain ASCII set, except the following ones: control
            characters, whitespace, &, ?, / and #.'
          example: Bcn-Welt
          maxLength: 256
          minLength: 1
          title: Entity Id
          type: string
        type:
          anyOf:
          - type: string
          - enum: []
            title: Enum
          description: 'Id of an entity in an NGSI context broker. Allowed characters
            are the ones in the plain ASCII set, except the following ones: control
            characters, whitespace, &, ?, / and #.'
          example: Room
          maxLength: 256
          minLength: 1
          title: Entity Type
      required:
      - id
      - type
      title: ActuatorFiware
      type: object
