openapi: 3.0.1
info:
  title: CO2SensorFiware
  description: API specification for IoT platform including C O2 Sensor Fiwares
  version: '1.0'
servers:
- url: http://fiware.rwth-aachen.de/
paths:
  /v2/entities:
    get:
      tags:
      - C O2 Sensor Fiware
      summary: Get C O2 Sensor Fiwares
      description: Retrieves available c o2 sensor fiwares
      operationId: getCO2SensorFiwares
      parameters:
      - name: type
        in: query
        description: Entity type, to avoid ambiguity in case there are several entities
          with the same entity id.
        schema:
          type: string
          default: CO2SensorFiware
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '200':
          description: Successful operation. Returns the CO2 measurement.
          content:
            text/plain:
              schema:
                type: number
                format: float
              example: 400
        '404':
          description: C O2 Sensor Fiware not found.
          content: {}
        '500':
          description: Internal server error.
          content: {}
    post:
      tags:
      - C O2 Sensor Fiware
      summary: Create C O2 Sensor Fiware
      description: Creates a new C O2 Sensor Fiware entity in the system.
      operationId: createCO2SensorFiware
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CO2SensorFiware'
            example:
              id: co2sensorfiware001
              type: CO2SensorFiware
              co2:
                value: 400
      parameters:
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '201':
          description: C O2 Sensor Fiware successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CO2SensorFiware'
        '400':
          description: Invalid input data.
          content: {}
        '500':
          description: Internal server error.
          content: {}
components:
  schemas:
    CO2SensorFiware:
      additionalProperties: true
      description: Extends the CO2Sensor class to include Fiware-specific properties.
      properties:
        id:
          description: 'Id of an entity in an NGSI context broker. Allowed characters
            are the ones in the plain ASCII set, except the following ones: control
            characters, whitespace, &, ?, / and #.'
          example: Bcn-Welt
          maxLength: 256
          minLength: 1
          title: Entity Id
          type: string
        type:
          default: CO2Sensor
          title: Type
          type: string
        hasLocation:
          default: null
          title: Haslocation
          type: string
        co2:
          anyOf:
          - type: number
          - type: 'null'
          default: 0
          title: Co2
      required:
      - id
      title: CO2SensorFiware
      type: object
