openapi: 3.0.1
info:
  title: TemperatureSensorAmbFiware
  description: API specification for IoT platform including Temperature Sensor Amb
    Fiwares
  version: '1.0'
servers:
- url: http://fiware.rwth-aachen.de/
paths:
  /v2/entities:
    get:
      tags:
      - Temperature Sensor Amb Fiware
      summary: Get Temperature Sensor Amb Fiwares
      description: Retrieves available temperature sensor amb fiwares
      operationId: getTemperatureSensorAmbFiwares
      parameters:
      - name: type
        in: query
        description: Entity type, to avoid ambiguity in case there are several entities
          with the same entity id.
        schema:
          type: string
          default: TemperatureSensorAmbFiware
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '200':
          description: Successful operation. Returns the temperature measurement.
          content:
            text/plain:
              schema:
                type: number
                format: float
              example: 22.5
        '404':
          description: Temperature Sensor Amb Fiware not found.
          content: {}
        '500':
          description: Internal server error.
          content: {}
    post:
      tags:
      - Temperature Sensor Amb Fiware
      summary: Create Temperature Sensor Amb Fiware
      description: Creates a new Temperature Sensor Amb Fiware entity in the system.
      operationId: createTemperatureSensorAmbFiware
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemperatureSensorAmbFiware'
            example:
              id: temperaturesensorambfiware001
              type: TemperatureSensorAmbFiware
              temperature:
                value: 22.5
      parameters:
      - name: Fiware-Service
        in: header
        required: true
        schema:
          type: string
          default: semantic_iot
      - name: Fiware-ServicePath
        in: header
        required: true
        schema:
          type: string
          default: /
      responses:
        '201':
          description: Temperature Sensor Amb Fiware successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemperatureSensorAmbFiware'
        '400':
          description: Invalid input data.
          content: {}
        '500':
          description: Internal server error.
          content: {}
components:
  schemas:
    TemperatureSensorAmbFiware:
      additionalProperties: true
      description: Extends the TemperatureSensorAmb class to include Fiware-specific
        properties.
      properties:
        id:
          description: 'Id of an entity in an NGSI context broker. Allowed characters
            are the ones in the plain ASCII set, except the following ones: control
            characters, whitespace, &, ?, / and #.'
          example: Bcn-Welt
          maxLength: 256
          minLength: 1
          title: Entity Id
          type: string
        type:
          default: AmbientTemperatureSensor
          title: Type
          type: string
        hasLocation:
          anyOf:
          - type: string
          - type: 'null'
          default: null
          title: Haslocation
        temperatureAmb:
          anyOf:
          - type: number
          - type: 'null'
          default: 0
          title: Temperatureamb
      required:
      - id
      title: TemperatureSensorAmbFiware
      type: object
